version: '3'

services:
  app1:
    build:
      context: ./app1
    ports:
      - "8081:5000"  # Assuming your Node.js app on website1 runs on port 3000

  app2:
    build:
      context: ./app2
    ports:
      - "8082:5001"